### ISSUE TITLE
Introduce support for Manjaro Linux

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/kernel-crawler#136]
**Motivation**

Manjaro is not supported right now.
Furthermore, the main consumer of kernel-crawler is the DBG of Falco, of which drivers would be beneficial to be distributed prebuilt on Manjaro machines, without needing to provision them with compiler toolkits. 

**Feature**

Introduce support to discover Manjaro-distributed Linux kernel releases.

**Alternatives**

Leverage the Arch Linux implementation, configuring <MIRROR_URL>/<MANJARO_DIST>/<REPO_PATH_URI>. (e.g. http://manjaro.ucom.am/stable/core/x86_64/).

I.e. Manjaro Dist is one of: [stable, unstable, testing, arm-stable, arm-unstable, arm-testing].
Repo Path URI are structured the same of Arch Linux ones as they are consumed by ALPM tools (e.g. pacman).

**Additional context**

NA

**Comment by FedeDP** [comment]
:+1: for this! 
It should be super simple too!
I am not sure whether we want to support prebuilt drivers for manjaro on test-infra, but falcosecurity is not the only consumer of crawled jsons, therefore i am all for it!

**Comment by FedeDP** [comment]
On a second note: we might want to move archlinux to only crawl latest kernels (instead of using archive.archlinux.org).
Archived repos make sense for driverkit (that needs to be able to build even old releases), but kernel-crawler should only find headers for kernel releases currently available in distro repositories IMHO.
We could then do the same for manjaro.

Moreover, arch uses a git mirroring; we should move to use it too: https://gitlab.archlinux.org/archlinux/packaging/packages/linux

EDIT: unfortunately, archlinux arm is not using the same git mirroring: https://archlinuxarm.org/packages/aarch64/linux-aarch64/files

**Comment by FedeDP** [comment]
I also discovered that:
* archlinuxarm has got `/usr/lib/os-release` but no `/etc/os-release` (used by `falco-driver-loader`).
* archlinuxarm os-release file looks like:
```
cat /usr/lib/os-release
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo
```
So, it has a different `ID` than the `arch` one.
Given that we don't support prebuilt for archlinux, this is not a big concern right now, but it would be good to address it in the future.

**Comment by FedeDP** [comment]
Since nobody asked for this from the community, we can close this one.
/close

Feel free to reopen if needed.
